# 8 AM UTC / 3 AM ET, delete if older than 2 hours
dailyRate: cron(0 8 ? * * *)
dailyStaleAfter: 2

# Every 1 hour, delete if older than 8 hours
hourlyRate: cron(0 */1 ? * * *)
hourlyStaleAfter: 8

# Stages and statuses to retain - consistent regardless of schedule
stagesToRetain: "['PROD', 'PRODUCTION', 'QA', 'DEVELOPMENT', 'DEV', 'AUTO', 'AUTOMATION', 'INFRA', 'INFRASTRUCTURE', 'COMMON']"
deleteableStatuses: "['CREATE_COMPLETE', 'ROLLBACK_COMPLETE', 'UPDATE_COMPLETE', 'UPDATE_ROLLBACK_COMPLETE']"

# CloudFormation output key of buckets to empty
bucketsToEmpty: "['ServerlessDeploymentBucketName', 'DocumentBucket']"
