service:
  name: odin

plugins:
  - serverless-plugin-iopipe
  - serverless-webpack
  - serverless-cloudformation-resource-counter
  - serverless-stack-output

provider:
  name: aws
  runtime: nodejs8.10
  stage: local
  environment:
    LOG_LEVEL:
      Fn::FindInMap: [ LogLevel, '${opt:stage, self:provider.stage}', level ]
    DELETE_STACK_TOPIC:
      Fn::Join:
        - ':'
        - - arn:aws:sns:us-east-1
          - Ref: AWS::AccountId
          - delete-stack-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

custom:
  odin: ${file(./odin.yml)}
  config: ${file(./infrastructure/configurations.yml)}
  # iopipeToken is used to forward monitoring information to IO Pipe
  iopipeToken: ${self:custom.config.iopipeToken}
  # output is used by the serverless-stack-output plugin
  output: { file: ./infrastructure/stack-outputs.yml }
  properties: ${file(./infrastructure/properties.yml)}

functions:

  checkStacks:
    handler: app/check.handler
    events:
      - schedule:
          rate: ${self:custom.dailyRate}
          input:
            staleAfter: ${self:custom.dailyStaleAfter}
            stagesToRetain: ${self:custom.stagesToRetain}
            deleteableStatuses: ${self:custom.deleteableStatuses}
      - schedule:
          rate: ${self:custom.hourlyRate}
          input:
            staleAfter: ${self:custom.hourlyStaleAfter}
            stagesToRetain: ${self:custom.stagesToRetain}
            deleteableStatuses: ${self:custom.deleteableStatuses}

  deleteStacks:
    handler: app/delete.handler
    events:
      - sns: delete-stack-${opt:stage, self:provider.stage}
    environment:
      BUCKETS_TO_EMPTY: ${self:custom.bucketsToEmpty}

resources:
  Description: Automated service for destroying temporary stacks (retains production, qa, development, and automation stacks)
  
  Outputs:

    DeleteStackSNS:
      Description: ARN of the ${opt:stage, self:provider.stage} stage SNS topic for stack deletion
      Value:
        Fn::Join:
          - ':'
          - - arn:aws:sns:us-east-1
            - Ref: AWS::AccountId
            - delete-stack-${opt:stage, self:provider.stage}
      Export:
        Name: odin-${opt:stage, self:provider.stage}-delete-stack-sns
