service: odin

custom: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: test
  environment:
    LOG_LEVEL:
      Fn::FindInMap: [ LogLevel, '${opt:stage, self:provider.stage}', level ]
    DELETE_STACK_TOPIC:
      Fn::Join:
        - ':'
        - - arn:aws:sns:us-east-1
          - Ref: AWS::AccountId
          - delete-stack-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: '*'

functions:
  CheckStacks:
    handler: stacks/check.handler
    events:
      - schedule:
          rate: ${self:custom.dailyRate}
          input:
            staleAfter: ${self:custom.dailyStaleAfter}
            stagesToRetain: ${self:custom.stagesToRetain}
            deleteableStatuses: ${self:custom.deleteableStatuses}
      - schedule:
          rate: ${self:custom.hourlyRate}
          input:
            staleAfter: ${self:custom.hourlyStaleAfter}
            stagesToRetain: ${self:custom.stagesToRetain}
            deleteableStatuses: ${self:custom.deleteableStatuses}

  DeleteStacks:
    handler: stacks/delete.handler
    events:
      - sns: delete-stack-${opt:stage, self:provider.stage}
    environment:
      BUCKETS_TO_EMPTY: ${self:custom.bucketsToEmpty}

resources:
  Description: Automated service for destroying temporary stacks (retains production and automation stacks)
  
  Mappings:
    LogLevel:
      test:
        level: debug
      local:
        level: debug
      automation:
        level: debug
      production:
        level: info
  
  Outputs:

    DeleteStackSNS:
      Description: ARN of the ${opt:stage, self:provider.stage} stage SNS topic for stack deletion
      Value:
        Fn::Join:
          - ':'
          - - arn:aws:sns:us-east-1
            - Ref: AWS::AccountId
            - delete-stack-${opt:stage, self:provider.stage}
      Export:
        Name: odin-${opt:stage, self:provider.stage}-delete-stack-sns
