CheckStacksLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:109092357768:function:odin-phillip-checkStacks:1'
DeleteStackSNS: 'arn:aws:sns:us-east-1:109092357768:delete-stack-phillip'
DeleteStacksLambdaFunctionQualifiedArn: 'arn:aws:lambda:us-east-1:109092357768:function:odin-phillip-deleteStacks:1'
ServerlessDeploymentBucketName: odin-phillip-serverlessdeploymentbucket-1ot7q3qmx7t72
